Error: FAIL
    at Timeout.setTimeout [as _onTimeout] (/scripts/promise-resolve-follow.js:r:c)
    at listOnTimeout (timers.js:r:c)
    at processTimers (timers.js:r:c)
    at new Promise (<anonymous>)
    at f1 (/scripts/promise-resolve-follow.js:r:c)
    at Promise (/scripts/promise-resolve-follow.js:r:c)
    at new Promise (<anonymous>)
    at f2 (/scripts/promise-resolve-follow.js:r:c)
    at Promise.resolve.then (/scripts/promise-resolve-follow.js:r:c)
    at process._tickCallback (internal/process/next_tick.js:r:c)
    at Function.Module.runMain (internal/modules/cjs/loader.js:r:c)
    at Promise.then (<anonymous>)
    at Promise.catch (<anonymous>)
    at f3 (/scripts/promise-resolve-follow.js:r:c)
    at Promise.then (<anonymous>)
    at f3 (/scripts/promise-resolve-follow.js:r:c)
    at Function.resolve (<anonymous>)
    at f3 (/scripts/promise-resolve-follow.js:r:c)
    at Object.<anonymous> (/scripts/promise-resolve-follow.js:r:c)
    at Module._compile (internal/modules/cjs/loader.js:r:c)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:r:c)
    at Module.load (internal/modules/cjs/loader.js:r:c)
    at tryModuleLoad (internal/modules/cjs/loader.js:r:c)
    at Function.Module._load (internal/modules/cjs/loader.js:r:c)
    at Function.Module.runMain (internal/modules/cjs/loader.js:r:c)
    at startup (internal/bootstrap/node.js:r:c)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:r:c)
